version: '3.8'

services:
  app:
    build: .
    image: fastapi-book-project
    volumes:
      - .:/app
    expose:
      - 9000
    environment:
      - PYTHONPATH=/app
    restart: always

  nginx:
    image: nginx:1.19-alpine
    ports:
       - "8080:80"  # Changed from 80 to 8080 to avoid conflicts
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

networks:
  default:
    driver: bridge

