name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker-compose build
          docker tag fastapi-book-project_app ${{ secrets.ACR_LOGIN_SERVER }}/fastapi-book-project:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/fastapi-book-project:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container create \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name fastapi-app \
              --image ${{ secrets.ACR_LOGIN_SERVER }}/fastapi-book-project:${{ github.sha }} \
              --dns-name-label fastapi-book-project \
              --ports 80